barebox: fix pkg-config for host tools
PKG_CONF_PATH must be set to STAGING_DIR_NATIVE instead of
STAGING_DIR_HOST to allow building host tools with library dependencies
such as imx-usb-loader that depends on libusb.h and otherwise fails
with:

| scripts/imx/imx-usb-loader.c:33:20: fatal error: libusb.h: No such file or directory
|  #include <libusb.h>
|                     ^
| compilation terminated.

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>